### PR TITLE
Convert to a litemod and implement the neighbor updating and pathfinding renderers

### PR DESCRIPTION
**Pull request by Pokechu22**
This PR converts this mod to a litemod (w/ mixins) and then adds support for the two debug renders that need plugin channels.

* Neighbor updating: This was actually quite easy to implement and works very well.  (Try it with a long line of redstone)
* Pathfinding: this was actually a lot harder than I expected and doesn't work perfectly.  The actual path being taken (including node types) renders just fine, though I don't update it with the current position on that path yet.  However, the information outside of that path is not rendered.  There are fields that supposedly contain that information, but they're never set (I'm not sure how those fields were named).  To fully implement this channel, a lot of extra mixins would be needed - possible, but I'm not ready to do that quite yet.

Both of those channels won't work on multiplayer.  And, in fact, `MC|DebugNeighborsUpdate` is impossible to use on multiplayer due to the length of its name (which is really odd).  But for singleplayer, they're fine.

### CODE REVIEW

**Comment by Fadenfire** [comment]
[I think you forgot to add a ref-map.](https://gist.github.com/Silly511/28428c6b62a6cef703b3e9096ccc82ec)

Anyway, I don't think I'll merge this yet. I've never used mixins or done much with liteloader, so I don't know if I can maintain this very well if I do merge it. I don't want to have code in my mod that I can't understand and can't debug. Would it be ok with you if I posted the litemod on CurseForge(once you've fixed that crash), but linked back to your fork for bug reports? I'll try to learn more about litemod development and mixins so I can maintain this myself.

**Comment by Pokechu22** [comment]
Hm, that's odd.  I'd have thought that the refmap would be generated; it is automatically generated in most other cases.  I'll check and try to handle this tomorrow.  (I only tested in my development environment; I probably should have tried it with launching the game too).  A quick check shows that it's generating a file named `mixin.refmap.json` instead of `mixins.ExtendedDebugRenders.json`, but I don't know why yet.

Regarding splitting between the two: I'm not sure what the best way of handling that is.  Could link to my fork, or could keep it here.  Could be in either place.  If wanted, it wouldn't be super hard to maintain both a litemod and forge version as subprojects using forgegradle (I could set that up pretty easily).

Mixins have a quite nice wiki [here](https://github.com/SpongePowered/Mixin/wiki).  It's not 100% complete, but it explains what they're designed to do fairly well.  I'd recommend reading over it.  For litemods themselves, I don't have any great documentation on hand but liteloader itself isn't used too deeply (just as a way to get code called each tick and to load the mixins).

**Comment by Pokechu22** [comment]
Belay that, just did a very brief check and it turns out that the refmap was just not being generated because I missed a simple line in the buildscript (der).  I still haven't tested this ingame but everything should work now.  (Note that you need to do a clean build (`gradle clean build`) for this to work right, otherwise it assumes it's already been generated)

**Comment by Fadenfire** [comment]
Added that block to the build.gradle, still getting exact same error. Opening the litemod shows that the refmap file does exist, but for some reason it's still not being loaded. [Here's](https://www.dropbox.com/s/2ogwgjpz8lxy5s3/mod-extendeddebugrenders-1.12.1-1.2-mc1.12.1.litemod?dl=1) the litemod file, did I build it wrong? I just used `gradle clean build`.

**Comment by Pokechu22** [comment]
You built it right.  Turns out I made a second typo.

The file it's looking for is named `mixins.ExtendedDebugRenderers.refmap.json`.  Note that it's "render**er**s".  However, I'm creating just "renders".

Fixed.  That was a typo that I should have caught had I tried to run it myself.  Everything's **edit**: starting fine on my machine now.

Looks like the fact that the refmap isn't being generated each time if just doing `build` and not `clean build` is also a MixinGradle bug (SpongePowered/MixinGradle#4) which is fixed in `0.5-SNAPSHOT`.  Updated.

**Comment by Fadenfire** [comment]
Works now, except for one thing. The first time I tried it I got this crash when I loaded a world:
<pre>java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.World.handler$onNeighborChanged$zza000(World.java:4052)
	at net.minecraft.world.World.func_190524_a(World.java)
	at net.minecraft.world.World.func_175685_c(World.java:490)
	at net.minecraft.world.World.func_175722_b(World.java:438)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:379)
	at net.minecraft.world.World.func_180501_a(World.java:359)
	at net.minecraft.block.BlockDaylightDetector.func_180677_d(SourceFile:78)
	at net.minecraft.tileentity.TileEntityDaylightDetector.func_73660_a(SourceFile:16)
	at net.minecraft.world.World.func_72939_s(World.java:1811)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)</pre>
My best guess is that a block update was triggered on the server before the client joined, so on line 20 in MixinWorld `Minecraft.getMinecraft().world` returned null. Do you think changing it to `((World)this).getTotalWorldTime()` might fix that?

**Comment by Fadenfire** [comment]
Actually it may be `Minecraft.getMinecraft().getConnection()` that's null. I got two crashes, one from the client:
<pre>java.net.ConnectException: connection refused: local:E:65389694
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:490)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:512)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:255)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:274)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)</pre>
And one from the server which is the one I posted above.

**Comment by Pokechu22** [comment]
> Do you think changing it to `((World)this).getTotalWorldTime()` might fix that?

Yea, I think that'd work.  (you may need to do `((World)(Object)this)` due to the way mixins work as javac assumes that directly casting to `Object` would never work)

**Comment by Pokechu22** [comment]
Oh, yea, connection might be null.  I check to make that it's not null on the pathfinder mixin, but it seems like I'm not doing that for the update one.

**Comment by Fadenfire** [comment]
Let's hope that fixed it, I don't think there's anything else that could be null and there's not a good way to test it since you'd have to trigger a block update at just the right time. I'm going to post this on CurseForge now.

**Pull request merged**
